# Stage 1
# Create image based on the official Node 8 image from dockerhub

# FROM node:8.11.2-alpine as node
FROM node:latest as node
# RUN apk update && apk add --no-cache make git
RUN npm install -g yarn  --force
WORKDIR /app
COPY ./ /app/
COPY package*.json ./
RUN yarn 
# RUN npm i 
# RUN yarn upgrade
# RUN npm install -g npm@7.17.0
# RUN npm run build 
RUN yarn build 

# MULTI STAGE
FROM nginx:alpine
COPY --from=node /app/dist/diseaseApp /usr/share/nginx/html
COPY ./nginx-custom.conf /etc/nginx/conf.d/default.conf